# Generated by Django 5.2 on 2026-08-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_department_user_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subteam',
            field=models.CharField(blank=True, help_text='Sub-team the employee belongs to (e.g. SCADA, Vision) - set by admin.', max_length=100),
        ),
    ]
