# Generated by Django 5.2 on 2026-08-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Each email address can belong to only one user account.', max_length=254, unique=True),
        ),
    ]
