# Generated by Django 5.2 on 2026-08-19 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskupdate',
            constraint=models.UniqueConstraint(fields=('task', 'employee', 'date', 'half'), name='unique_task_employee_date_half'),
        ),
    ]
