# Generated by Django 5.2 on 2026-08-21 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_notification_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('release_at', models.DateTimeField(help_text='When this task becomes a real, visible task for the employee.')),
                ('released', models.BooleanField(default=False)),
                ('batch_id', models.CharField(help_text='Groups tasks created together in one batch (same title, staggered release).', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduled_tasks', to=settings.AUTH_USER_MODEL)),
                ('released_task', models.OneToOneField(blank=True, help_text='The real Task created once this was released.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_source', to='tasks.task')),
            ],
            options={
                'ordering': ['release_at'],
            },
        ),
    ]
