# Generated by Django 5.2 on 2026-08-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='on_hold',
            field=models.BooleanField(default=False, help_text='If true, this task will NOT auto-release even if its time has passed, until an admin resumes it.'),
        ),
    ]
